spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:file:D:\programowanie_rozwoj\Java\spring-learn\test
    username: sa
    password: test
  jpa:
    show-sql: true


